import type { AppContext } from '../types'
import { agendaConfigRef, child, get, oradoresCadastroRef, oradoresCongregacoesRef, oradoresEventosRef, oradoresProgramacaoRef, oradoresRef, oradoresTemasRef, set, tarefasPeopleRef, tarefasPlanejamentoRef, update } from '../firebase'
import { renderWorkspaceNav } from '../ui/workspace-nav'
import { moduleBackButton } from '../ui/module-header'
import { lockPublicationUi } from '../ui/publication-busy'
import { defaultModuleMessageSettings, mountModuleMessageSettings, type ModuleMessageSettings } from './module-message-settings'
import {
  EVENT_KIND_LABEL, SPEAKER_ROLE_LABEL, TALK_KIND_LABEL, TALK_STATUS_LABEL,
  formatSpeakerDate, monthBounds, newSpeakerId, normalizeSpeakerEvents, normalizeSpeakersRoot, selectSecondSection,
  phoneDigits, sameMonth, scheduleCongregationId, scheduleCongregationName, scheduleStatus,
  speakerPendingItems, validIsoDate,
  type Speaker, type SpeakerCongregation, type SpeakerEvent, type SpeakerEventKind,
  type SpeakerRole, type SpeakersRoot, type TalkKind, type TalkSchedule, type TalkTheme,
} from './oradores-domain'

type Screen = 'programacao' | 'temas' | 'eventos' | 'oradores' | 'designacoes' | 'congregacoes' | 'intercambios' | 'pendencias' | 'emergencia'
type Planning = { meetingDays?:{ weekendDow?:number; weekendS1Dow?:number }; excludedDates?:string[]; enableSection1?:boolean; s1Time?:string; s2Time?:string }
type TaskPerson = { name?:string; active?:boolean }

let screen: Screen = 'programacao'
let data: SpeakersRoot = {}
let events: Record<string, SpeakerEvent> = {}
let planning: Planning = {}
let taskPeople: Record<string, TaskPerson> = {}
let selectedMonth = localStorage.getItem('noroeste_oradores_month') ?? new Date().toISOString().slice(0, 7)
let editingId = ''
let scheduleDraft: Record<string, string> | null = null
let selectedSpeakerId = ''
let selectedCongregationId = ''
let loadPromise: Promise<boolean> | null = null
let downloadingPdf = false
let publishingPdf = false
let hideLowPending = localStorage.getItem('noroeste_oradores_hide_low_pending') === '1'
let messageSettings = defaultModuleMessageSettings('oradores')

const esc = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char] ?? char))
const root = (): HTMLElement => document.getElementById('oradoresRoot')!
const speakers = (): Record<string, Speaker> => data.oradores ?? {}
const themes = (): Record<string, TalkTheme> => data.temas ?? {}
const congregations = (): Record<string, SpeakerCongregation> => data.congregacoes ?? {}
const schedule = (): Record<string, TalkSchedule> => data.programacao ?? {}
const toast = (message: string): void => { const element=document.getElementById('toast'); if (!element) return; element.textContent=message; element.classList.add('show'); setTimeout(()=>element.classList.remove('show'), 3000) }
function openWhatsapp(phone:string, message:string):boolean { const digits=phoneDigits(phone); if(digits.length<12){toast('Cadastre um telefone válido antes de abrir o WhatsApp');return false} window.open(`https://wa.me/${digits}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');return true }
function applyMessageTemplate(template:string, details:string, name='irmãos'):string { return template.split('{dados_da_reuniao}').join(details).split('{nome}').join(name) }
function scheduleMessage(item:TalkSchedule):string { const speaker=speakers()[item.oradorId??''],theme=themes()[item.temaId??''],congregation=congregations()[scheduleCongregationId(item)],details=[`Data: ${formatSpeakerDate(item.data)}`,theme||item.temaTitulo?`Tema: ${theme?`${theme.numero} - ${theme.titulo}`:item.temaTitulo}`:'Tema: a definir',item.tipo==='saida_orador'?`Congregação: ${congregation?.nome??scheduleCongregationName(item)??'a definir'}`:`Horário: ${item.horarioLocal||'a confirmar'}`].join('\n');return applyMessageTemplate(messageSettings.meetingText,details,speaker?.nome??item.oradorNome??'irmão') }
const option = (value:string, label:string, selected:string): string => `<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`
const field = (label:string, control:string, help=''): string => `<label class="form-field"><span>${esc(label)}</span>${control}${help ? `<small>${esc(help)}</small>` : ''}</label>`
const sectionTitle = (title:string): string => `<div class="module-section-title">${screen === 'programacao' ? '' : moduleBackButton()}<h2>${esc(title)}</h2></div>`
const empty = (message:string): string => `<p class="empty-state">${esc(message)}</p>`
const isoNow = (): string => new Date().toISOString()

export default function mount(_: AppContext): void {
  screen='programacao'; editingId=''; scheduleDraft=null; loadPromise=null; data={}; events={}; planning={}; taskPeople={}
  const host=document.getElementById('appContent'); if (!host) return
  host.innerHTML='<div id="oradoresNav"></div><div id="oradoresRoot"></div>'
  void openScreen('programacao')
}

async function load(): Promise<boolean> {
  try {
    const [rootSnapshot,eventSnapshot,planningSnapshot,peopleSnapshot,messageSnapshot]=await Promise.all([get(oradoresRef), get(oradoresEventosRef), get(tarefasPlanejamentoRef), get(tarefasPeopleRef), get<ModuleMessageSettings>(child(agendaConfigRef,'moduleWhatsApp/oradores'))])
    data=selectSecondSection(normalizeSpeakersRoot(rootSnapshot.exists()?rootSnapshot.val():{}))
    events=normalizeSpeakerEvents(eventSnapshot.exists()?eventSnapshot.val():{})
    planning=planningSnapshot.exists() ? planningSnapshot.val() as Planning : {}
    taskPeople=peopleSnapshot.exists() ? peopleSnapshot.val() as Record<string,TaskPerson> : {}
    messageSettings={...defaultModuleMessageSettings('oradores'),...(messageSnapshot.exists()?messageSnapshot.val()??{}:{})}
    selectedSpeakerId=selectedSpeakerId && speakers()[selectedSpeakerId] ? selectedSpeakerId : Object.entries(speakers()).sort((a,b)=>a[1].nome.localeCompare(b[1].nome,'pt-BR'))[0]?.[0] ?? ''
    selectedCongregationId=selectedCongregationId && congregations()[selectedCongregationId] ? selectedCongregationId : Object.entries(congregations()).filter(([,item])=>item.tipo==='visitante').sort((a,b)=>a[1].nome.localeCompare(b[1].nome,'pt-BR'))[0]?.[0] ?? ''
    return true
  } catch { toast('Não foi possível carregar Oradores'); return false }
}

async function openScreen(next: Screen): Promise<void> {
  screen=next; editingId=''; renderNavigation(); root().innerHTML='<p class="empty-state">Carregando dados...</p>'
  loadPromise ??= load()
  const loaded=await loadPromise
  if (!root().isConnected || screen!==next) return
  if (!loaded) { loadPromise=null; root().innerHTML='<p class="empty-state">Não foi possível carregar os dados.</p><button id="retrySpeakers" class="btn btn-primary">Tentar novamente</button>'; document.getElementById('retrySpeakers')?.addEventListener('click',()=>void openScreen(next)); return }
  render()
}

function renderNavigation(): void {
  const host=document.getElementById('oradoresNav'); if (!host) return
  renderWorkspaceNav(host, 'Oradores', 'programacao', screen, [
    { id:'programacao', label:'Programação' },
    { id:'oradores', label:'Oradores', children:[{id:'oradores',label:'Cadastro'},{id:'designacoes',label:'Designações'},{id:'emergencia',label:'Emergência'}] },
    { id:'congregacoes', label:'Congregações', children:[{id:'congregacoes',label:'Cadastro'},{id:'intercambios',label:'Intercâmbios'}] },
    { id:'temas', label:'Apoio', children:[{id:'temas',label:'Temas'},{id:'eventos',label:'Eventos'},{id:'pendencias',label:'Pendências'}] },
  ], id=>void openScreen(id as Screen))
}

function render(): void {
  renderNavigation()
  if (screen==='programacao') renderSchedule()
  else if (screen==='oradores') renderSpeakers()
  else if (screen==='temas') renderThemes()
  else if (screen==='congregacoes') renderCongregations()
  else if (screen==='eventos') renderEvents()
  else if (screen==='designacoes') renderAssignments()
  else if (screen==='intercambios') renderExchanges()
  else if (screen==='pendencias') renderPending()
  else renderEmergency()
}

function periodControl(): string {
  return `<div class="agenda-toolbar oradores-period"><button id="oradoresPrev" class="btn btn-ghost" type="button" aria-label="Mês anterior">‹</button><input id="oradoresMonth" class="form-input" type="month" value="${esc(selectedMonth)}"><button id="oradoresNext" class="btn btn-ghost" type="button" aria-label="Próximo mês">›</button></div>`
}
function bindPeriod(): void {
  const move=(delta:number):void=>{ const [year,month]=selectedMonth.split('-').map(Number), date=new Date(Date.UTC(year!,month!-1+delta,1)); selectedMonth=date.toISOString().slice(0,7); localStorage.setItem('noroeste_oradores_month',selectedMonth); renderSchedule() }
  document.getElementById('oradoresPrev')?.addEventListener('click',()=>move(-1)); document.getElementById('oradoresNext')?.addEventListener('click',()=>move(1))
  document.getElementById('oradoresMonth')?.addEventListener('change',event=>{ const value=(event.currentTarget as HTMLInputElement).value; if (/^\d{4}-\d{2}$/.test(value)) { selectedMonth=value; localStorage.setItem('noroeste_oradores_month',value); renderSchedule() } })
}

function speakerOptions(selected='', kind?:'local'|'visitante'): string {
  return `<option value="">A definir</option>${Object.entries(speakers()).filter(([,item])=>item.ativo && (!kind || item.tipo===kind)).sort((a,b)=>a[1].nome.localeCompare(b[1].nome,'pt-BR')).map(([id,item])=>option(id,item.nome,selected)).join('')}`
}
function themeOptions(selected=''): string { return `<option value="">A definir</option>${Object.entries(themes()).filter(([,item])=>item.ativo || selected).sort((a,b)=>a[1].numero-b[1].numero).map(([id,item])=>option(id,`${String(item.numero).padStart(3,'0')} - ${item.titulo}`,selected)).join('')}` }
function congregationOptions(selected=''): string { return `<option value="">A definir</option>${Object.entries(congregations()).filter(([,item])=>item.ativa && item.tipo==='visitante').sort((a,b)=>a[1].nome.localeCompare(b[1].nome,'pt-BR')).map(([id,item])=>option(id,item.nome,selected)).join('')}` }

function scheduleEditor(): string {
  if (!editingId) return ''
  const item=editingId==='new' ? undefined : schedule()[editingId]
  const draft=scheduleDraft, kind=(draft?.['tipo'] as TalkKind|undefined) ?? item?.tipo ?? 'discurso_local', congregationId=draft?.['congregacaoId'] ?? (item ? scheduleCongregationId(item) : '')
  return `<form id="speakerScheduleForm" class="form-panel"><h3>${item?'Editar programação':'Nova programação'}</h3><div class="module-form-grid">
    ${field('Tipo',`<select name="tipo">${Object.entries(TALK_KIND_LABEL).map(([id,label])=>option(id,label,kind)).join('')}</select>`)}
    ${field('Data',`<input name="data" type="date" value="${esc(draft?.['data'] ?? item?.data ?? `${selectedMonth}-01`)}" required>`)}
    ${field(kind==='discurso_visitante'?'Visitante':'Orador',`<select name="oradorId">${speakerOptions(draft?.['oradorId']??item?.oradorId,kind==='discurso_visitante'?'visitante':'local')}</select>`)}
    ${kind==='discurso_visitante' ? field('Nome digitado (se não cadastrado)',`<input name="oradorNome" maxlength="100" value="${esc(draft?.['oradorNome']??item?.oradorNome)}">`) : ''}
    ${kind!=='discurso_local' ? field(kind==='saida_orador'?'Congregação de destino':'Congregação de origem',`<select name="congregacaoId">${congregationOptions(congregationId)}</select>`) : ''}
    ${field('Tema',`<select name="temaId">${themeOptions(draft?.['temaId']??item?.temaId)}</select>`)}
    ${kind==='discurso_local' ? field('Segundo orador',`<select name="oradorSecundarioId">${speakerOptions(draft?.['oradorSecundarioId']??item?.oradorSecundarioId,'local')}</select>`) : ''}
    ${kind!=='saida_orador' ? field('Horário local',`<input name="horarioLocal" type="time" value="${esc(draft?.['horarioLocal']??item?.horarioLocal ?? planning.s2Time ?? '')}">`) : ''}
    ${field('Observações',`<textarea name="observacoes" maxlength="500">${esc(draft?.['observacoes']??item?.observacoes)}</textarea>`)}
  </div><div class="service-actions"><button class="btn btn-primary" type="submit">Salvar</button><button id="cancelScheduleEdit" class="btn btn-ghost" type="button">Cancelar</button>${item?'<button id="deleteSchedule" class="btn btn-danger" type="button">Excluir</button>':''}</div></form>`
}

function scheduleCard(id:string,item:TalkSchedule): string {
  const speaker=speakers()[item.oradorId??'']?.nome ?? item.oradorNome ?? 'Sem orador', theme=themes()[item.temaId??''], congregation=congregations()[scheduleCongregationId(item)]?.nome ?? scheduleCongregationName(item)
  const status=scheduleStatus(item), section=''
  return `<article class="oradores-card"><div class="oradores-card-head"><div><strong>${esc(formatSpeakerDate(item.data))}</strong><small>${esc(TALK_KIND_LABEL[item.tipo]+section)}</small></div><span class="status-pill status-${esc(status)}">${esc(TALK_STATUS_LABEL[status])}</span></div><div class="oradores-card-grid"><div><span>Orador</span><strong>${esc(speaker)}</strong></div><div><span>Tema</span><strong>${theme?`${String(theme.numero).padStart(3,'0')} - ${theme.titulo}`:item.temaTitulo||'Sem tema'}</strong></div>${congregation?`<div><span>Congregação</span><strong>${esc(congregation)}</strong></div>`:''}${item.oradorSecundarioNome?`<div><span>Segundo orador</span><strong>${esc(item.oradorSecundarioNome)}</strong></div>`:''}</div><div class="service-actions"><button class="btn btn-ghost" data-edit-schedule="${esc(id)}">Editar</button><button class="btn btn-ghost" data-confirm-schedule="${esc(id)}">${status==='confirmado'?'Desfazer confirmação':'Confirmar'}</button>${status==='confirmado' ? `<button class="btn btn-ghost" data-reconfirm-schedule="${esc(id)}">${item.reconfirmacao?.status?'Desfazer reconfirmação':'Reconfirmar'}</button>`:''}${id?`<button class="btn btn-ghost" data-notify-schedule="${esc(id)}">Abrir WhatsApp</button>`:''}</div></article>`
}

function renderSchedule(): void {
  const rows=Object.entries(schedule()).filter(([,item])=>sameMonth(item.data,selectedMonth)).sort((a,b)=>a[1].data.localeCompare(b[1].data)||a[1].tipo.localeCompare(b[1].tipo))
  root().innerHTML=`${sectionTitle('Programação de oradores')}${periodControl()}<div class="service-actions"><button id="newSchedule" class="btn btn-primary" type="button">Nova programação</button><button id="fillScheduleDates" class="btn btn-ghost" type="button">Criar datas do mês</button><button id="speakerSchedulePdf" class="btn btn-ghost" type="button" ${rows.length?'':'disabled'}>Baixar PDF A4</button><button id="speakerSchedulePublish" class="btn btn-ghost" type="button" ${rows.length?'':'disabled'}>Publicar no Quadro</button></div>${scheduleEditor()}<div class="oradores-list">${rows.map(([id,item])=>scheduleCard(id,item)).join('')||empty('Nenhuma programação neste mês.')}</div><div id="oradoresMessageSettings"></div>`
  bindPeriod()
  document.getElementById('newSchedule')?.addEventListener('click',()=>{ editingId='new'; scheduleDraft=null; renderSchedule() })
  document.getElementById('fillScheduleDates')?.addEventListener('click',()=>void createMonthSlots())
  document.getElementById('speakerSchedulePdf')?.addEventListener('click',()=>void downloadSchedulePdf())
  document.getElementById('speakerSchedulePublish')?.addEventListener('click',()=>void publishSchedulePdf())
  document.getElementById('cancelScheduleEdit')?.addEventListener('click',()=>{ editingId=''; scheduleDraft=null; renderSchedule() })
  document.getElementById('speakerScheduleForm')?.addEventListener('change',event=>{ if ((event.target as HTMLElement).getAttribute('name')==='tipo') void saveDraftAndRerender(event.currentTarget as HTMLFormElement) })
  document.getElementById('speakerScheduleForm')?.addEventListener('submit',event=>{ event.preventDefault(); void saveSchedule(event.currentTarget as HTMLFormElement) })
  document.getElementById('deleteSchedule')?.addEventListener('click',()=>void deleteSchedule())
  document.querySelectorAll<HTMLButtonElement>('[data-edit-schedule]').forEach(button=>button.addEventListener('click',()=>{ editingId=button.dataset.editSchedule!; scheduleDraft=null; renderSchedule() }))
  document.querySelectorAll<HTMLButtonElement>('[data-confirm-schedule]').forEach(button=>button.addEventListener('click',()=>void toggleConfirmation(button.dataset.confirmSchedule!)))
  document.querySelectorAll<HTMLButtonElement>('[data-reconfirm-schedule]').forEach(button=>button.addEventListener('click',()=>void toggleReconfirmation(button.dataset.reconfirmSchedule!)))
  document.querySelectorAll<HTMLButtonElement>('[data-notify-schedule]').forEach(button=>button.addEventListener('click',()=>void notifySchedule(button.dataset.notifySchedule!)))
  void mountModuleMessageSettings('oradoresMessageSettings','oradores',toast,settings=>{messageSettings=settings})
}

function saveDraftAndRerender(form:HTMLFormElement): void {
  const values=new FormData(form)
  scheduleDraft=Object.fromEntries([...values.entries()].filter(([,value])=>typeof value==='string').map(([key,value])=>[key,String(value)]))
  renderSchedule()
}

async function saveSchedule(form:HTMLFormElement): Promise<void> {
  const values=new FormData(form), kind=String(values.get('tipo')) as TalkKind, date=String(values.get('data')), speakerId=String(values.get('oradorId')??''), themeId=String(values.get('temaId')??''), congregationId=String(values.get('congregacaoId')??''), secondId=String(values.get('oradorSecundarioId')??''), section='s2'
  if (!validIsoDate(date)) { toast('Informe uma data válida'); return }
  const duplicate=Object.entries(schedule()).find(([id,item])=>id!==editingId && item.data===date && item.tipo===kind && (kind==='saida_orador'||(item.secao??'s2')===section))
  if (duplicate) { toast('Já existe uma programação igual nesta data'); return }
  const speaker=speakers()[speakerId], theme=themes()[themeId], congregation=congregations()[congregationId], second=speakers()[secondId]
  const manualName=String(values.get('oradorNome')??'').trim(), now=isoNow(), previous=editingId==='new'||editingId==='__draft__'?undefined:schedule()[editingId]
  const status=previous?.status==='confirmado'?'confirmado':speakerId||manualName?'por_confirmar':'por_definir'
  const item:TalkSchedule={ ...previous, data:date, tipo:kind, status, updatedAt:now, ...(section&&kind!=='saida_orador'?{secao:section as 's1'|'s2'}:{}), ...(speakerId?{oradorId:speakerId,oradorNome:speaker?.nome}:manualName?{oradorNome:manualName}:{}), ...(theme?{temaId:themeId,temaNumero:theme.numero,temaTitulo:theme.titulo}:{}), ...(second?{oradorSecundarioId:secondId,oradorSecundarioNome:second.nome,oradorSecundarioTipo:second.tipo}:{}), ...(kind==='saida_orador'&&congregation?{congregacaoDestinoId:congregationId,congregacaoDestinoNome:congregation.nome}:kind==='discurso_visitante'&&congregation?{congregacaoOrigemId:congregationId,congregacaoOrigemNome:congregation.nome}:{}), ...(kind!=='saida_orador'&&String(values.get('horarioLocal')??'')?{horarioLocal:String(values.get('horarioLocal'))}:{}), ...(String(values.get('observacoes')??'').trim()?{observacoes:String(values.get('observacoes')).trim()}:{}), ...(status==='confirmado'?{confirmacao:previous?.confirmacao??{status:true,confirmadoEm:now}}:{confirmacao:{status:false,confirmadoEm:''}}) }
  const id=previous?editingId:newSpeakerId('programacao')
  try { await set(child(oradoresProgramacaoRef,id),item); schedule()[id]=item; editingId=''; scheduleDraft=null; toast(previous?'Programação atualizada':'Programação criada'); renderSchedule() } catch { toast('Não foi possível salvar a programação') }
}

async function deleteSchedule(): Promise<void> { const id=editingId, item=schedule()[id]; if (!item||!confirm(`Excluir a programação de ${formatSpeakerDate(item.data)}?`)) return; try { await set(child(oradoresProgramacaoRef,id),null); delete schedule()[id]; editingId=''; toast('Programação excluída'); renderSchedule() } catch { toast('Não foi possível excluir') } }
async function toggleConfirmation(id:string): Promise<void> { const item=schedule()[id]; if (!item) return; const confirmed=scheduleStatus(item)==='confirmado', status=confirmed?(item.oradorId||item.oradorNome?'por_confirmar':'por_definir'):'confirmado', confirmation={status:!confirmed,confirmadoEm:confirmed?'':isoNow()}; try { await update(child(oradoresProgramacaoRef,id),{status,confirmacao:confirmation,updatedAt:isoNow()}); item.status=status; item.confirmacao=confirmation; renderSchedule() } catch { toast('Não foi possível alterar a confirmação') } }
async function toggleReconfirmation(id:string): Promise<void> { const item=schedule()[id]; if (!item) return; const value=!item.reconfirmacao?.status, reconfirmacao={status:value,confirmadoEm:value?isoNow():''}; try { await update(child(oradoresProgramacaoRef,id),{reconfirmacao,updatedAt:isoNow()}); item.reconfirmacao=reconfirmacao; renderSchedule() } catch { toast('Não foi possível alterar a reconfirmação') } }
async function notifySchedule(id:string):Promise<void>{const item=schedule()[id],speaker=item?speakers()[item.oradorId??'']:undefined;if(!item||!speaker||!openWhatsapp(speaker.telefone,scheduleMessage(item)))return;const avisadoEm=isoNow();try{await update(child(oradoresProgramacaoRef,id),{avisadoEm});item.avisadoEm=avisadoEm}catch{toast('O WhatsApp abriu, mas não foi possível registrar o aviso')}}

function blockedDate(date:string): boolean { return planning.excludedDates?.includes(date)===true || Object.values(events).some(item=>item.data===date&&item.tipo!=='informativo') }
async function createMonthSlots(): Promise<void> {
  const {start,end}=monthBounds(selectedMonth), startDate=new Date(`${start}T12:00:00Z`), endDate=new Date(`${end}T12:00:00Z`), sections:(readonly ['s2',number,string])[] = [['s2',planning.meetingDays?.weekendDow??0,planning.s2Time??'']]
  const patch:Record<string,unknown>={}
  for (const [section,dow,time] of sections) for (let date=new Date(startDate); date<=endDate; date.setUTCDate(date.getUTCDate()+1)) { const iso=date.toISOString().slice(0,10); if (date.getUTCDay()!==dow||blockedDate(iso)||Object.values(schedule()).some(item=>item.data===iso&&item.tipo!=='saida_orador'&&(item.secao??'s2')===section)) continue; const id=newSpeakerId('programacao'), local=Object.entries(congregations()).find(([,item])=>item.tipo==='local'&&(item.secao??'s2')===section); patch[id]={data:iso,tipo:'discurso_local',status:'por_definir',secao:section,horarioLocal:time,...(local?{localCongregacaoId:local[0],localCongregacaoNome:local[1].nome}:{}),updatedAt:isoNow()} }
  if (!Object.keys(patch).length) { toast('Todas as datas do mês já estão criadas'); return }
  try { await update(oradoresProgramacaoRef,patch); Object.assign(schedule(),patch); toast(`${Object.keys(patch).length} data(s) criada(s)`); renderSchedule() } catch { toast('Não foi possível criar as datas') }
}

async function downloadSchedulePdf(): Promise<void> {
  if (downloadingPdf) return; downloadingPdf=true
  const button=document.getElementById('speakerSchedulePdf') as HTMLButtonElement|null; if(button){button.disabled=true;button.textContent='Preparando PDF...'}
  try { const docs=await import('./oradores-documents'); await docs.downloadSpeakersSchedulePdf({month:selectedMonth,schedule:Object.values(schedule()),speakers:speakers(),themes:themes(),congregations:congregations()}); toast('Download do PDF iniciado') } catch { toast('Não foi possível gerar o PDF') } finally { downloadingPdf=false; if(button){button.disabled=false;button.textContent='Baixar PDF A4'} }
}

async function publishSchedulePdf(): Promise<void> {
  if (publishingPdf) return
  publishingPdf=true
  const releaseUi=lockPublicationUi()
  try {
    const [{ createSpeakersSchedulePdf },{ publishAgendaModulePdf }]=await Promise.all([import('./oradores-documents'),import('./agenda-documents')])
    const bytes=await createSpeakersSchedulePdf({month:selectedMonth,schedule:Object.values(schedule()),speakers:speakers(),themes:themes(),congregations:congregations()})
    const {end}=monthBounds(selectedMonth)
    await publishAgendaModulePdf(bytes,{modulo:'oradores',periodo:selectedMonth,inicio:`${selectedMonth}-01`,fim:end,origemPeriodoId:selectedMonth,nome:`programacao-oradores-${selectedMonth}.pdf`})
    toast('PDF de Oradores publicado no Quadro')
  } catch { toast('Não foi possível publicar o PDF') }
  finally { publishingPdf=false; releaseUi() }
}

function speakerEditor(): string {
  if (!editingId) return ''; const item=editingId==='new'?undefined:speakers()[editingId]
  const themeChecks=Object.entries(themes()).filter(([id,theme])=>theme.ativo||item?.temaIds.includes(id)).sort((a,b)=>a[1].numero-b[1].numero).map(([id,theme])=>`<label class="oradores-check"><input name="temaId" type="checkbox" value="${esc(id)}" ${item?.temaIds.includes(id)?'checked':''}><span>${String(theme.numero).padStart(3,'0')} - ${esc(theme.titulo)}</span></label>`).join('')
  const sectionField=''
  return `<form id="speakerForm" class="form-panel"><h3>${item?'Editar orador':'Novo orador'}</h3><div class="module-form-grid">${field('Nome',`<input name="nome" maxlength="100" value="${esc(item?.nome)}" required>`)}${field('Tipo',`<select name="tipo">${option('local','Local',item?.tipo??'local')}${option('visitante','Visitante',item?.tipo??'local')}</select>`)}${field('Função',`<select name="funcao">${Object.entries(SPEAKER_ROLE_LABEL).map(([id,label])=>option(id,label,item?.funcao??'anciao')).join('')}</select>`)}${field('Telefone',`<input name="telefone" inputmode="tel" value="${esc(item?.telefone)}">`)}${field('Participante vinculado',`<select name="pessoaId"><option value="">Nenhum</option>${Object.entries(taskPeople).filter(([,person])=>person.active!==false).sort((a,b)=>(a[1].name??'').localeCompare(b[1].name??'','pt-BR')).map(([id,person])=>option(id,person.name??id,item?.pessoaId??'')).join('')}</select>`)}${field('Congregação',`<select name="congregacaoId"><option value="">Nenhuma</option>${Object.entries(congregations()).sort((a,b)=>a[1].nome.localeCompare(b[1].nome,'pt-BR')).map(([id,c])=>option(id,c.nome,item?.congregacaoId??'')).join('')}</select>`)}${sectionField}</div><div class="oradores-check-grid"><label class="oradores-check"><input name="ativo" type="checkbox" ${item?.ativo!==false?'checked':''}> Ativo</label><label class="oradores-check"><input name="aprovadoParaSaida" type="checkbox" ${item?.aprovadoParaSaida?'checked':''}> Aprovado para saída</label><label class="oradores-check"><input name="podePresidir" type="checkbox" ${item?.podePresidir?'checked':''}> Pode presidir</label><label class="oradores-check"><input name="sentinelaDirigente" type="checkbox" ${item?.sentinelaDirigente?'checked':''}> Dirigente de A Sentinela</label><label class="oradores-check"><input name="sentinelaSubstituto" type="checkbox" ${item?.sentinelaSubstituto?'checked':''}> Substituto de A Sentinela</label></div><details><summary>Repertório de temas · ${item?.temaIds.length??0}</summary><div class="oradores-check-grid">${themeChecks||empty('Nenhum tema ativo.')}</div></details><div class="service-actions"><button class="btn btn-primary" type="submit">Salvar</button><button id="cancelSpeakerEdit" class="btn btn-ghost" type="button">Cancelar</button>${item?'<button id="deleteSpeaker" class="btn btn-danger" type="button">Excluir</button>':''}</div></form>`
}
function renderSpeakers(): void {
  const rows=Object.entries(speakers()).sort((a,b)=>Number(b[1].ativo)-Number(a[1].ativo)||a[1].nome.localeCompare(b[1].nome,'pt-BR'))
  root().innerHTML=`${sectionTitle('Cadastro de oradores')}<div class="service-actions"><button id="newSpeaker" class="btn btn-primary">Novo orador</button></div>${speakerEditor()}<div class="oradores-list">${rows.map(([id,item])=>`<article class="oradores-card"><div class="oradores-card-head"><div><strong>${esc(item.nome)}</strong><small>${esc(item.tipo==='local'?'Local':item.origemNome||'Visitante')} · ${esc(SPEAKER_ROLE_LABEL[item.funcao])}</small></div><span class="status-pill">${item.ativo?'Ativo':'Inativo'}</span></div><div class="oradores-card-grid"><div><span>Telefone</span><strong>${esc(item.telefone||'Não informado')}</strong></div><div><span>Temas</span><strong>${item.temaIds.length}</strong></div><div><span>Saída</span><strong>${item.aprovadoParaSaida?'Aprovado':'Não aprovado'}</strong></div><div><span>A Sentinela</span><strong>${item.sentinelaDirigente?'Dirigente':item.sentinelaSubstituto?'Substituto':'-'}</strong></div></div><button class="btn btn-ghost" data-edit-speaker="${esc(id)}">Editar</button></article>`).join('')||empty('Nenhum orador cadastrado.')}</div>`
  document.getElementById('newSpeaker')?.addEventListener('click',()=>{editingId='new';renderSpeakers()}); document.getElementById('cancelSpeakerEdit')?.addEventListener('click',()=>{editingId='';renderSpeakers()}); document.getElementById('speakerForm')?.addEventListener('submit',event=>{event.preventDefault();void saveSpeaker(event.currentTarget as HTMLFormElement)}); document.getElementById('deleteSpeaker')?.addEventListener('click',()=>void deleteSpeaker()); document.querySelectorAll<HTMLButtonElement>('[data-edit-speaker]').forEach(button=>button.addEventListener('click',()=>{editingId=button.dataset.editSpeaker!;renderSpeakers()}))
}
async function saveSpeaker(form:HTMLFormElement):Promise<void>{ const values=new FormData(form), name=String(values.get('nome')).trim(); if(!name){toast('Informe o nome');return} const id=editingId==='new'?newSpeakerId('orador'):editingId, item:Speaker={nome:name,tipo:String(values.get('tipo')) as 'local'|'visitante',funcao:String(values.get('funcao')) as SpeakerRole,telefone:phoneDigits(String(values.get('telefone'))),ativo:values.get('ativo')==='on',temaIds:values.getAll('temaId').map(String),...(String(values.get('pessoaId'))?{pessoaId:String(values.get('pessoaId'))}:{}),...(String(values.get('congregacaoId'))?{congregacaoId:String(values.get('congregacaoId'))}:{}),secao:'s2',aprovadoParaSaida:values.get('aprovadoParaSaida')==='on',podePresidir:values.get('podePresidir')==='on',sentinelaDirigente:values.get('sentinelaDirigente')==='on',sentinelaSubstituto:values.get('sentinelaSubstituto')==='on'}; const patch:Record<string,unknown>={[id]:item}; Object.entries(speakers()).filter(([otherId,other])=>otherId!==id&&(other.secao??'s2')===(item.secao??'s2')).forEach(([otherId])=>{if(item.sentinelaDirigente)patch[`${otherId}/sentinelaDirigente`]=false;if(item.sentinelaSubstituto)patch[`${otherId}/sentinelaSubstituto`]=false}); try{await update(oradoresCadastroRef,patch);speakers()[id]=item;editingId='';toast('Orador salvo');renderSpeakers()}catch{toast('Não foi possível salvar')}}
async function deleteSpeaker():Promise<void>{const id=editingId,item=speakers()[id];if(!item||!confirm(`Excluir ${item.nome}? O histórico da programação será preservado.`))return;try{await set(child(oradoresCadastroRef,id),null);delete speakers()[id];editingId='';renderSpeakers()}catch{toast('Não foi possível excluir')}}

function themeEditor():string{if(!editingId)return'';const item=editingId==='new'?undefined:themes()[editingId];return`<form id="themeForm" class="form-panel"><h3>${item?'Editar tema':'Novo tema'}</h3><div class="module-form-grid">${field('Número',`<input name="numero" type="number" min="1" max="999" value="${item?.numero??''}" required>`)}${field('Título',`<input name="titulo" maxlength="180" value="${esc(item?.titulo)}" required>`)}</div><label class="oradores-check"><input name="ativo" type="checkbox" ${item?.ativo!==false?'checked':''}> Tema ativo</label><div class="service-actions"><button class="btn btn-primary">Salvar</button><button id="cancelThemeEdit" class="btn btn-ghost" type="button">Cancelar</button>${item?'<button id="deleteTheme" class="btn btn-danger" type="button">Excluir</button>':''}</div></form>`}
function renderThemes():void{const usages=new Map<string,string[]>();Object.values(schedule()).forEach(item=>{if(item.temaId){const list=usages.get(item.temaId)??[];list.push(item.data);usages.set(item.temaId,list)}});const rows=Object.entries(themes()).sort((a,b)=>a[1].numero-b[1].numero);root().innerHTML=`${sectionTitle('Temas')}<button id="newTheme" class="btn btn-primary">Novo tema</button>${themeEditor()}<div class="module-option-list">${rows.map(([id,item])=>{const dates=(usages.get(id)??[]).sort();return`<article class="oradores-row"><div><strong>${String(item.numero).padStart(3,'0')} - ${esc(item.titulo)}</strong><small>${item.ativo?'Ativo':'Inativo'} · ${dates.length?`Último uso: ${formatSpeakerDate(dates[dates.length-1]!)}`:'Nunca usado'}</small></div><button class="btn btn-ghost" data-edit-theme="${esc(id)}">Editar</button></article>`}).join('')||empty('Nenhum tema cadastrado.')}</div>`;document.getElementById('newTheme')?.addEventListener('click',()=>{editingId='new';renderThemes()});document.getElementById('cancelThemeEdit')?.addEventListener('click',()=>{editingId='';renderThemes()});document.getElementById('themeForm')?.addEventListener('submit',event=>{event.preventDefault();void saveTheme(event.currentTarget as HTMLFormElement)});document.getElementById('deleteTheme')?.addEventListener('click',()=>void deleteTheme());document.querySelectorAll<HTMLButtonElement>('[data-edit-theme]').forEach(button=>button.addEventListener('click',()=>{editingId=button.dataset.editTheme!;renderThemes()}))}
async function saveTheme(form:HTMLFormElement):Promise<void>{const values=new FormData(form),number=Number(values.get('numero')),title=String(values.get('titulo')).trim();if(!Number.isInteger(number)||number<1||number>999||!title){toast('Informe número e título válidos');return}if(Object.entries(themes()).some(([id,item])=>id!==editingId&&item.numero===number)){toast('Já existe um tema com este número');return}const id=editingId==='new'?`tema_${String(number).padStart(3,'0')}`:editingId,item={numero:number,titulo:title,ativo:values.get('ativo')==='on'};try{await set(child(oradoresTemasRef,id),item);themes()[id]=item;editingId='';renderThemes()}catch{toast('Não foi possível salvar')}}
async function deleteTheme():Promise<void>{const id=editingId,item=themes()[id];if(!item||Object.values(schedule()).some(row=>row.temaId===id)){toast('Tema com histórico deve ser inativado, não excluído');return}if(!confirm(`Excluir o tema ${item.numero}?`))return;try{await set(child(oradoresTemasRef,id),null);delete themes()[id];editingId='';renderThemes()}catch{toast('Não foi possível excluir')}}

function congregationEditor():string{if(!editingId)return'';const item=editingId==='new'?undefined:congregations()[editingId];return`<form id="congregationForm" class="form-panel"><h3>${item?'Editar congregação':'Nova congregação'}</h3><div class="module-form-grid">${field('Nome',`<input name="nome" value="${esc(item?.nome)}" required>`)}${field('Cidade',`<input name="cidade" value="${esc(item?.cidade)}">`)}${field('Tipo',`<select name="tipo">${option('visitante','Visitante',item?.tipo??'visitante')}${option('local','Local',item?.tipo??'visitante')}</select>`)}${field('Contato',`<input name="contato" value="${esc(item?.contato)}">`)}${field('Telefone',`<input name="telefone" inputmode="tel" value="${esc(item?.telefone)}">`)}${field('Dia da reunião',`<input name="diaReuniao" placeholder="Sábado" value="${esc(item?.diaReuniao)}">`)}${field('Horário',`<input name="horario" type="time" value="${esc(item?.horario)}">`)}${field('Localização',`<input name="localizacao" value="${esc(item?.localizacao)}">`)}${field('Observações',`<textarea name="observacoes">${esc(item?.observacoes)}</textarea>`)}</div><label class="oradores-check"><input name="ativa" type="checkbox" ${item?.ativa!==false?'checked':''}> Congregação ativa</label><div class="service-actions"><button class="btn btn-primary">Salvar</button><button id="cancelCongregationEdit" class="btn btn-ghost" type="button">Cancelar</button>${item?'<button id="deleteCongregation" class="btn btn-danger" type="button">Excluir</button>':''}</div></form>`}
function renderCongregations():void{const rows=Object.entries(congregations()).sort((a,b)=>a[1].nome.localeCompare(b[1].nome,'pt-BR'));root().innerHTML=`${sectionTitle('Congregações')}<button id="newCongregation" class="btn btn-primary">Nova congregação</button>${congregationEditor()}<div class="oradores-list">${rows.map(([id,item])=>`<article class="oradores-card"><div class="oradores-card-head"><div><strong>${esc(item.nome)}</strong><small>${esc([item.tipo==='local'?'Local':'Visitante',item.cidade].filter(Boolean).join(' · '))}</small></div><span class="status-pill">${item.ativa?'Ativa':'Inativa'}</span></div><div class="oradores-card-grid"><div><span>Contato</span><strong>${esc(item.contato||'Não informado')}</strong></div><div><span>Telefone</span><strong>${esc(item.telefone||'Não informado')}</strong></div><div><span>Reunião</span><strong>${esc([item.diaReuniao,item.horario].filter(Boolean).join(' às ')||'Não informada')}</strong></div><div><span>Localização</span><strong>${esc(item.localizacao||'Não informada')}</strong></div></div><button class="btn btn-ghost" data-edit-congregation="${esc(id)}">Editar</button></article>`).join('')||empty('Nenhuma congregação cadastrada.')}</div>`;document.getElementById('newCongregation')?.addEventListener('click',()=>{editingId='new';renderCongregations()});document.getElementById('cancelCongregationEdit')?.addEventListener('click',()=>{editingId='';renderCongregations()});document.getElementById('congregationForm')?.addEventListener('submit',event=>{event.preventDefault();void saveCongregation(event.currentTarget as HTMLFormElement)});document.getElementById('deleteCongregation')?.addEventListener('click',()=>void deleteCongregation());document.querySelectorAll<HTMLButtonElement>('[data-edit-congregation]').forEach(button=>button.addEventListener('click',()=>{editingId=button.dataset.editCongregation!;renderCongregations()}))}
async function saveCongregation(form:HTMLFormElement):Promise<void>{const values=new FormData(form),name=String(values.get('nome')).trim();if(!name){toast('Informe o nome');return}const id=editingId==='new'?newSpeakerId('congregacao'):editingId,item:SpeakerCongregation={nome:name,cidade:String(values.get('cidade')).trim(),tipo:String(values.get('tipo')) as 'local'|'visitante',ativa:values.get('ativa')==='on',contato:String(values.get('contato')).trim(),telefone:phoneDigits(String(values.get('telefone'))),diaReuniao:String(values.get('diaReuniao')).trim(),horario:String(values.get('horario')),localizacao:String(values.get('localizacao')).trim(),observacoes:String(values.get('observacoes')).trim(),secao:'s2'};try{await set(child(oradoresCongregacoesRef,id),item);congregations()[id]=item;editingId='';renderCongregations()}catch{toast('Não foi possível salvar')}}
async function deleteCongregation():Promise<void>{const id=editingId,item=congregations()[id];if(!item||Object.values(schedule()).some(row=>scheduleCongregationId(row)===id)){toast('Congregação com histórico deve ser inativada, não excluída');return}if(!confirm(`Excluir ${item.nome}?`))return;try{await set(child(oradoresCongregacoesRef,id),null);delete congregations()[id];editingId='';renderCongregations()}catch{toast('Não foi possível excluir')}}

function eventEditor():string{if(!editingId)return'';const item=editingId==='new'?undefined:events[editingId],types=item?.impactoTarefas?.tiposReuniao??[];return`<form id="speakerEventForm" class="form-panel"><h3>${item?'Editar evento':'Novo evento'}</h3><div class="module-form-grid">${field('Data',`<input name="data" type="date" value="${esc(item?.data??`${selectedMonth}-01`)}" required>`)}${field('Título',`<input name="titulo" value="${esc(item?.titulo)}" required>`)}${field('Tipo',`<select name="tipo">${Object.entries(EVENT_KIND_LABEL).map(([id,label])=>option(id,label,item?.tipo??'informativo')).join('')}</select>`)}${field('Descrição',`<textarea name="descricao">${esc(item?.descricao)}</textarea>`)}</div><label class="oradores-check"><input name="bloqueiaReuniao" type="checkbox" ${item?.impactoTarefas?.bloqueiaReuniao?'checked':''}> Bloqueia reunião no módulo Tarefas</label><div class="oradores-check-grid"><label class="oradores-check"><input name="tipoReuniao" type="checkbox" value="midweek" ${types.includes('midweek')?'checked':''}> Meio de semana</label><label class="oradores-check"><input name="tipoReuniao" type="checkbox" value="weekend" ${types.includes('weekend')?'checked':''}> Fim de semana</label></div><div class="service-actions"><button class="btn btn-primary">Salvar</button><button id="cancelEventEdit" class="btn btn-ghost" type="button">Cancelar</button>${item?'<button id="deleteEvent" class="btn btn-danger" type="button">Excluir</button>':''}</div></form>`}
function renderEvents():void{const rows=Object.entries(events).sort((a,b)=>a[1].data.localeCompare(b[1].data));root().innerHTML=`${sectionTitle('Eventos')}<button id="newSpeakerEvent" class="btn btn-primary">Novo evento</button>${eventEditor()}<div class="module-option-list">${rows.map(([id,item])=>`<article class="oradores-row"><div><strong>${esc(item.titulo)}</strong><small>${esc(formatSpeakerDate(item.data))} · ${esc(EVENT_KIND_LABEL[item.tipo])}${item.impactoTarefas?.bloqueiaReuniao?' · Bloqueia Tarefas':''}</small></div><button class="btn btn-ghost" data-edit-event="${esc(id)}">Editar</button></article>`).join('')||empty('Nenhum evento cadastrado.')}</div>`;document.getElementById('newSpeakerEvent')?.addEventListener('click',()=>{editingId='new';renderEvents()});document.getElementById('cancelEventEdit')?.addEventListener('click',()=>{editingId='';renderEvents()});document.getElementById('speakerEventForm')?.addEventListener('submit',event=>{event.preventDefault();void saveEvent(event.currentTarget as HTMLFormElement)});document.getElementById('deleteEvent')?.addEventListener('click',()=>void deleteEvent());document.querySelectorAll<HTMLButtonElement>('[data-edit-event]').forEach(button=>button.addEventListener('click',()=>{editingId=button.dataset.editEvent!;renderEvents()}))}
async function saveEvent(form:HTMLFormElement):Promise<void>{const values=new FormData(form),date=String(values.get('data')),title=String(values.get('titulo')).trim(),blocks=values.get('bloqueiaReuniao')==='on',selectedTypes=values.getAll('tipoReuniao').map(String);if(!validIsoDate(date)||!title){toast('Informe data e título válidos');return}if(blocks&&!selectedTypes.length){toast('Escolha qual reunião será bloqueada');return}const tiposReuniao=[...selectedTypes];const id=editingId==='new'?newSpeakerId('evento'):editingId,item:SpeakerEvent={data:date,titulo:title,descricao:String(values.get('descricao')).trim(),tipo:String(values.get('tipo')) as SpeakerEventKind,impactoTarefas:{bloqueiaReuniao:blocks,tiposReuniao}};try{await set(child(oradoresEventosRef,id),item);events[id]=item;editingId='';renderEvents()}catch{toast('Não foi possível salvar')}}
async function deleteEvent():Promise<void>{const id=editingId,item=events[id];if(!item||!confirm(`Excluir ${item.titulo}?`))return;try{await set(child(oradoresEventosRef,id),null);delete events[id];editingId='';renderEvents()}catch{toast('Não foi possível excluir')}}

function contextSelect(kind:'speaker'|'congregation'):string{if(kind==='speaker')return`<label class="form-field context-select"><span>Orador</span><select id="speakerContext">${Object.entries(speakers()).sort((a,b)=>a[1].nome.localeCompare(b[1].nome,'pt-BR')).map(([id,item])=>option(id,item.nome,selectedSpeakerId)).join('')}</select></label>`;return`<label class="form-field context-select"><span>Congregação</span><select id="congregationContext">${Object.entries(congregations()).filter(([,item])=>item.tipo==='visitante').sort((a,b)=>a[1].nome.localeCompare(b[1].nome,'pt-BR')).map(([id,item])=>option(id,item.nome,selectedCongregationId)).join('')}</select></label>`}
function renderAssignments():void{const speaker=speakers()[selectedSpeakerId],rows=Object.values(schedule()).filter(item=>item.data>=new Date().toISOString().slice(0,10)&&(item.oradorId===selectedSpeakerId||item.oradorSecundarioId===selectedSpeakerId)).sort((a,b)=>a.data.localeCompare(b.data));root().innerHTML=`${sectionTitle('Designações')}${contextSelect('speaker')}${speaker&&rows.length?'<button id="notifySpeakerAssignments" class="btn btn-primary">Abrir no WhatsApp</button>':''}<div class="oradores-list">${speaker?rows.map(item=>scheduleCard('',item).replace(/<div class="service-actions">[\s\S]*?<\/div><\/article>$/,'</article>')).join('')||empty(`${speaker.nome} não tem compromissos futuros.`):empty('Nenhum orador selecionado.')}</div>`;document.getElementById('speakerContext')?.addEventListener('change',event=>{selectedSpeakerId=(event.currentTarget as HTMLSelectElement).value;renderAssignments()});document.getElementById('notifySpeakerAssignments')?.addEventListener('click',()=>{if(speaker){const details=rows.map(item=>`- ${formatSpeakerDate(item.data)}: ${TALK_KIND_LABEL[item.tipo]} - ${themes()[item.temaId??'']?.titulo??item.temaTitulo??'tema a definir'}`).join('\n');openWhatsapp(speaker.telefone,applyMessageTemplate(messageSettings.meetingText,details,speaker.nome))}})}
function renderExchanges():void{const today=new Date().toISOString().slice(0,10),allRows=Object.values(schedule()).filter(item=>item.data>=today&&item.tipo!=='discurso_local').sort((a,b)=>a.data.localeCompare(b.data)),congregation=congregations()[selectedCongregationId],rows=allRows.filter(item=>scheduleCongregationId(item)===selectedCongregationId),incoming=allRows.filter(item=>item.tipo==='discurso_visitante').length,outgoing=allRows.filter(item=>item.tipo==='saida_orador').length,congregationCount=new Set(allRows.map(scheduleCongregationId).filter(Boolean)).size,next=allRows[0];root().innerHTML=`${sectionTitle('Intercâmbios')}<div class="service-summary"><div><strong>${incoming}</strong><span>Entradas</span></div><div><strong>${outgoing}</strong><span>Saídas</span></div><div><strong>${congregationCount}</strong><span>Congregações</span></div><div><strong>${next?esc(formatSpeakerDate(next.data)):'-'}</strong><span>Próximo intercâmbio</span></div></div>${contextSelect('congregation')}${congregation&&rows.length?'<button id="notifyCongregationExchanges" class="btn btn-primary">Abrir no WhatsApp</button>':''}<div class="oradores-list">${congregation?rows.map(item=>scheduleCard('',item).replace(/<div class="service-actions">[\s\S]*?<\/div><\/article>$/,'</article>')).join('')||empty(`Nenhum intercâmbio futuro com ${congregation.nome}.`):empty('Nenhuma congregação selecionada.')}</div>`;document.getElementById('congregationContext')?.addEventListener('change',event=>{selectedCongregationId=(event.currentTarget as HTMLSelectElement).value;renderExchanges()});document.getElementById('notifyCongregationExchanges')?.addEventListener('click',()=>{if(congregation){const details=rows.map(item=>`- ${formatSpeakerDate(item.data)}: ${item.tipo==='saida_orador'?'vai':'vem'} ${speakers()[item.oradorId??'']?.nome??item.oradorNome??'orador a definir'}`).join('\n');openWhatsapp(congregation.telefone,applyMessageTemplate(messageSettings.meetingText,details,congregation.contato||'irmãos'))}})}
function renderPending():void{const allRows=speakerPendingItems(data),rows=hideLowPending?allRows.filter(item=>item.severity!=='baixa'):allRows;root().innerHTML=`${sectionTitle('Pendências')}<label class="oradores-check"><input id="hideLowPending" type="checkbox" ${hideLowPending?'checked':''}> Ocultar pendências de baixa prioridade</label><div class="oradores-list">${rows.map(item=>`<button class="oradores-pending severity-${item.severity}" data-pending-screen="${item.screen}" data-pending-id="${esc(item.recordId)}"><span><strong>${esc(item.title)}</strong><small>${esc(item.detail)}</small></span><span>›</span></button>`).join('')||empty(hideLowPending&&allRows.length?'Nenhuma pendência prioritária.':'Tudo em dia - nenhuma pendência.')}</div>`;document.getElementById('hideLowPending')?.addEventListener('change',event=>{hideLowPending=(event.currentTarget as HTMLInputElement).checked;localStorage.setItem('noroeste_oradores_hide_low_pending',hideLowPending?'1':'0');renderPending()});document.querySelectorAll<HTMLButtonElement>('[data-pending-screen]').forEach(button=>button.addEventListener('click',()=>{const next=button.dataset.pendingScreen as Screen,recordId=button.dataset.pendingId??'';void openScreen(next).then(()=>{if(next==='programacao'||next==='oradores'||next==='congregacoes'){editingId=recordId;render()}})}))}
function unavailableThemeIds():Set<string>{const cutoff='2026-05-16',used=new Set<string>();Object.values(data.historicoTemas??{}).forEach(item=>{if(item.temaId&&((item.data<cutoff&&item.historicoCompartilhado===true)||(item.data>=cutoff&&item.secao!=='s1')))used.add(item.temaId)});Object.values(schedule()).forEach(item=>{if(!item.temaId||item.tipo==='saida_orador'||item.secao==='s1')return;if(item.data<cutoff&&item.secao!=='s2'&&item.historicoCompartilhado!==true)return;used.add(item.temaId)});return used}
function renderEmergency():void{const used=unavailableThemeIds(),rows=Object.entries(speakers()).filter(([,item])=>item.tipo==='local'&&item.ativo).map(([id,item])=>({id,item,available:item.temaIds.filter(themeId=>Boolean(themes()[themeId]?.ativo&&!used.has(themeId))).map(themeId=>themes()[themeId] as TalkTheme)})).filter(row=>row.available.length).sort((a,b)=>a.item.nome.localeCompare(b.item.nome,'pt-BR'));root().innerHTML=`${sectionTitle('Emergência')}<p class="form-help">Oradores locais ativos e temas aprovados que não foram usados nem estão programados.</p><div class="oradores-list">${rows.map(row=>`<article class="oradores-card"><strong>${esc(row.item.nome)}</strong><small>${row.available.map(theme=>`${String(theme.numero).padStart(3,'0')} - ${esc(theme.titulo)}`).join('<br>')}</small></article>`).join('')||empty('Nenhum orador tem tema disponível no momento.')}</div>`}
